***************
*** 1,7 ****
- NAME = weaveworksdemos/catalogue
  DBNAME = weaveworksdemos/catalogue-db
  
- TAG=$(TRAVIS_COMMIT)
  
  INSTANCE = catalogue
  
--- 1,7 ----
+ NAME = gcr.io/kavach-builds/sock-shop/catalogue
  DBNAME = weaveworksdemos/catalogue-db
  
+ TAG=latest
  
  INSTANCE = catalogue
  
***************
*** 10,16 ****
  default: test
  
  release:
- 	docker build -t $(NAME) -f ./docker/catalogue/Dockerfile .
  
  test:
  	GROUP=weaveworksdemos COMMIT=test ./scripts/build.sh
--- 10,17 ----
  default: test
  
  release:
+ 	docker build -t $(NAME):$(TAG) -f ./docker/catalogue/Dockerfile .
+ 	docker push $(NAME):$(TAG)
  
  test:
  	GROUP=weaveworksdemos COMMIT=test ./scripts/build.sh
